# Generated by Django 4.1.13 on 2024-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_user_registration_delete_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='user_registration',
        ),
    ]
