# Generated by Django 4.1.13 on 2024-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_userregistration_delete_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
