# Generated by Django 4.1.13 on 2024-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_alter_userregistration_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='dues',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30)),
                ('due_amount', models.BigIntegerField()),
                ('last_payment_amount', models.BigIntegerField()),
            ],
        ),
    ]
